# TEST CRUD #

GET http://localhost:5000/


# AUTH #
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "nama_depan": "Rosa",
    "nama_belakang": "Amalia",
    "email": "rosaamalia@mail.com",
    "password": "password",
    "bidang_seni": "61dbf9ade7a6183c0786149c"
}

POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "nama_depan": "Riggina",
    "nama_belakang": "Oceania",
    "email": "riggina@mail.com",
    "password": "password",
    "bidang_seni": "61dbf9ade7a6183c0786149c"
}

POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "riggina@mail.com",
    "password": "password"
}

POST http://localhost:5000/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVG9rZW4iOnsiaWQiOiI2MWRkMGE0NWYwNTUzNGQ3MjcxN2ZjM2EiLCJlbWFpbCI6InJvc2FhbWFsaWFAbWFpbC5jb20ifSwiaWF0IjoxNjQxODc5NjM2LCJleHAiOjE2NDE4ODE0MzZ9.F_6dtzqEjQ-6B0ILMeF9AcSk0twbkE2v6Qz7whxz56A




# KELAS #

POST http://localhost:5000/kelas
Content-Type: application/json

{
    "bidang_seni": "seni lukis",
    "nama_kelas": "Berekspresi dengan Lukisan",
    "deskripsi": "Melukis adalah kegiatan mengolah medium dua dimensi atau permukaan dari objek tiga dimensi untuk mendapat kesan tertentu. Medium lukisan bisa berbentuk apa saja, seperti kanvas, kertas, papan, dan bahkan film di dalam fotografi bisa dianggap sebagai media lukisan. Alat yang digunakan juga bisa bermacam-macam, dengan syarat bisa memberikan imaji tertentu kepada media yang digunakan.",
    "foto_kelas": "path/to/lukis.jpg",
    "nama_mentor": "Amy Zahrawaan",
    "foto_mentor": "path/to/amyzahrawaan.jpg"
}

GET http://localhost:5000/kelas

GET http://localhost:5000/kelas/61dbf8aee7a6183c07861495

PUT http://localhost:5000/kelas/61dbf8aee7a6183c07861495
Content-Type: application/json

{
    "bidang_seni": "seni lukis",
    "nama_kelas": "Berekspresi dengan Lukisan",
    "deskripsi": "Melukis adalah kegiatan mengolah medium dua dimensi atau permukaan dari objek tiga dimensi untuk mendapat kesan tertentu.",
    "foto_kelas": "path/to/lukis.jpg",
    "nama_mentor": "Amy Zahrawaan",
    "foto_mentor": "path/to/amyzahrawaan.jpg"
}

DELETE http://localhost:5000/kelas/61dbf8aee7a6183c07861495




# USER #

POST http://localhost:5000/user
Content-Type: application/json

{
    "nama_depan" : "Rosa",
    "nama_belakang" : "Amalia",
    "email" : "rosa@mail.com",
    "password" : "password",
    "foto_profil" : "path/to/profil.jpg",
    "bidang_seni" : "61dbf9ade7a6183c0786149c",
    "telepon" : "08122222222",
    "alamat" : "Jl. Kehidupan",
    "sekolah" : "SMA N 2",
    "jenis_kelamin" : "Perempuan",
    "tanggal_lahir" : "2002-03-15",
    "facebook" : "Rosa Amalia",
    "instagram" : "@rosaaa",
    "linkedin" : "/in/rosaamalia"
}

GET http://localhost:5000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVG9rZW4iOnsiaWQiOiI2MWRkMGE0NWYwNTUzNGQ3MjcxN2ZjM2EiLCJlbWFpbCI6InJvc2FhbWFsaWFAbWFpbC5jb20ifSwiaWF0IjoxNjQxODc5NjM2LCJleHAiOjE2NDE4ODE0MzZ9.F_6dtzqEjQ-6B0ILMeF9AcSk0twbkE2v6Qz7whxz56A


PUT http://localhost:5000/user/61dbfa5de7a6183c0786149f
Content-Type: application/json

{
    "nama_depan" : "Rosa",
    "nama_belakang" : "Amalia",
    "email" : "rosa@mail.com",
    "foto_profil" : "path/to/profil.jpg",
    "bidang_seni" : "61dbf9ade7a6183c0786149c",
    "telepon" : "08122222222",
    "alamat" : "Jl. Kayangan Riau",
    "sekolah" : "SMA N 2",
    "jenis_kelamin" : "Perempuan",
    "tanggal_lahir" : "2002-03-15",
    "facebook" : "Rosa Amalia",
    "instagram" : "@rosaaa",
    "linkedin" : "/in/rosaamalia"
}

DELETE http://localhost:5000/user/61dbfa5de7a6183c0786149f




# MODUL #

POST http://localhost:5000/modul
Content-Type: application/json

{
    "urutan_modul": 1,
    "kelas": "61dbf9ade7a6183c0786149c",
    "nama_modul": "Modul 01: Pandangan Filosofis Ki Hajar Dewantara dan Driyarkara tentang Pendidikan",
    "isi_modul": "test",
    "link_video": "https://youtu.be/RJYwVOXwn08"
}

POST http://localhost:5000/modul
Content-Type: application/json

{
    "urutan_modul": 2,
    "kelas": "61dbf9ade7a6183c0786149c",
    "nama_modul": "Modul 02: Pradigma Pendidikan Kontekstual",
    "isi_modul": "test",
    "link_video": "https://youtu.be/uK764rVASss"
}

POST http://localhost:5000/modul
Content-Type: application/json

{
    "urutan_modul": 3,
    "kelas": "61dbf9ade7a6183c0786149c",
    "nama_modul": "Modul 03: Transformasi Peran Guru",
    "isi_modul": "test",
    "link_video": "https://youtu.be/-knxtJxJJfs"
}

POST http://localhost:5000/modul
Content-Type: application/json

{
    "urutan_modul": 4,
    "kelas": "61dbf9ade7a6183c0786149c",
    "nama_modul": "Modul 04: Teknologi Digital Sebagai Sumber Pembelajaran",
    "isi_modul": "test",
    "link_video": "https://youtu.be/Lm4RAUZfu58"
}

POST http://localhost:5000/modul
Content-Type: application/json

{
    "urutan_modul": 5,
    "kelas": "61dbf9ade7a6183c0786149c",
    "nama_modul": "Modul 05: Pembelajaran Kontekstual Berbasis Projek",
    "isi_modul": "test",
    "link_video": "https://youtu.be/JmycffHZ9UI",
    "tugas": "test"
}

POST http://localhost:5000/modul
Content-Type: application/json

{
    "urutan_modul": 6,
    "kelas": "61dbf9ade7a6183c0786149c",
    "nama_modul": "Modul 06: Seni dan Budaya sebagai Media Artikulasi Pengetahuan",
    "isi_modul": "test",
    "link_video": "https://youtu.be/blmm179GUAs",
    "tugas": "test"
}

POST http://localhost:5000/modul
Content-Type: application/json

{
    "urutan_modul": 7,
    "kelas": "61dbf9ade7a6183c0786149c",
    "nama_modul": "Modul 07: Evaluasi dan Penilaian Pembelajaran Kontekstual",
    "isi_modul": "test",
    "link_video": "https://youtu.be/B-pKC-JCzgA",
    "tugas": "test"
}


###

GET http://localhost:5000/modul

PUT http://localhost:5000/modul/61dc0053c039b72a729cbbad
Content-Type: application/json

{
    "urutan_modul": 1,
    "kelas": "61dbf9ade7a6183c0786149c",
    "nama_modul": "Modul 01: Pandangan Filosofis Ki Hajar Dewantara dan Driyarkara tentang Pendidikan",
    "isi_modul": "test isi modul",
    "link_video": "bit.ly/wC1nbE"
}

DELETE http://localhost:5000/modul/61dc0053c039b72a729cbbad




# PROFILE

GET http://localhost:5000/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyVG9rZW4iOnsiaWQiOiI2MWRkNDI3ODI2ZDA4ZWFlNjZlNzlmZWEiLCJlbWFpbCI6InJpZ2dpbmFAbWFpbC5jb20ifSwiaWF0IjoxNjQxODk1NDY0LCJleHAiOjE2NDE4OTcyNjR9.hkF1cvuLG5MzFM8ge3kbFw_-rKPnxRRsRP7UiQ1HRDw